### ISSUE TITLE
Gateway fallback not working

### ISSUE THREAD

**Issue by e3eli3h** [moul/advanced-ssh-config#289] opened 2018-09-05 08:44 UTC
This is an awesome project, I like! ;-)

Gateway fallback is not working for me at all (and I'd really like it to!).

Here is my simple yml config:

```
hosts:

    hosta:
        HostName: example.org
        User: admin

    hostb:
        HostName: 192.168.1.3
        User: pi
        Gateways: [ direct, hosta ]
```

ssh to hosta works fine, however when I ssh to hostb which I expect to first try to connect directly to 192.168.1.3 and then via hosta on failure I get the following:

```
DEBU[0000] assh args: [hostb]
DEBU[0000] Loading config file '~/.ssh/assh.yml'
DEBU[0000] Loaded config file '~/.ssh/assh.yml' (0 + 2 => 2 hosts)
DEBU[0000] getHostByName direct matching: "hostb"
INFO[0000] Host hostb
INFO[0000]   Port 22
INFO[0000]   User pi
INFO[0000]   # HostName: 192.168.1.3
DEBU[0000] Host: {"Port":"22","User":"pi","HostName":"192.168.1.3","Gateways":["direct","hosta"],"Hooks":{}}
DEBU[0000] Proxying
DEBU[0000] Trying gateways: [direct hosta]
DEBU[0000] Preparing host object
DEBU[0000] Calling BeforeConnect hooks
DEBU[0000] Connecting to 192.168.1.3:22
INFO[0000]   # Gateways: [direct, hosta]
Connection timed out during banner exchange
```

Output of "assh info":
```
Debug mode (client): false
CLI Path: /usr/local/bin/assh
Go version: go1.10.3
OS/Arch: linux/amd64

RC files:
- ~/.ssh/assh.yml

Statistics:
- 2 hosts
- 0 templates
- 1 included files
```

This is v2.8.0 (not found in assh info output) running on Fedora 28.
Can someone please tell me what I am doing wrong?

I am trying to achieve the example of hostd from here: https://github.com/moul/advanced-ssh-config#using-gateways-from-configuration-file

Thank you!

**Comment by moul** [comment] 2018-09-06 12:04
Hi @e3eli3h, can you:
1. rebuild `assh`
2. add a `GatewayConnectTimeout: 2` in `hostb`
3. give a new try?

**Comment by e3eli3h** [comment] 2018-09-06 12:33
Using 2.8.0+dev (HEAD)
```
DEBU[0000] getHostByName direct matching: "hostb"       
INFO[0000] Host hostb                                   
INFO[0000]   Port 22                                    
INFO[0000]   User pi                                    
INFO[0000]   # HostName: 192.168.61.3                   
INFO[0000]   # Gateways: [direct, hosta]                
INFO[0000]   # GatewayConnectTimeout: 2                 
DEBU[0000] Host: {"Port":"22","User":"pi","HostName":"192.168.61.3","Gateways":["direct","hosta"],"Hooks":{},"GatewayConnectTimeout":2} 
DEBU[0000] Proxying                                     
DEBU[0000] Trying gateways: [direct hosta]              
2018/09/06 15:29:43 direct
DEBU[0000] Preparing host object                        
DEBU[0000] Calling BeforeConnect hooks                  
DEBU[0000] Connecting to 192.168.61.3:22                
Connection timed out during banner exchange
```

**Comment by moul** [comment] 2018-09-06 12:53
I can't reproduce this issue on my host, from what I read, it's an `ssh` generated message (not an `assh` one), maybe you have a global ConnectTimeout configured somewhere in your `/etc` directory?

You should also be able to ocnfigure it directly from `assh`:

```yaml
hosts:

    hosta:
        HostName: example.org
        User: admin

    hostb:
        HostName: 192.168.1.3
        User: pi
        Gateways: [ direct, hosta ]

    defaults:
        GatewayConnectionTimeout: 2 # assh gateway connect timeout
        ConnectTimeout: 20          # ssh connect timeout

```

**Comment by e3eli3h** [comment] 2018-09-06 14:38
Hi @moul,

You are totally correct that I had a ConnectTimeout set in a file under my /etc/ssh/ssh_config.d
Removing the entry altogether made everything spring to life.
Trouble is... I don't understand why this would have affected any and all settings I declare in my assh.yml file, including the defaults.

Sorry for the trouble and thanks for the help.
I can now begin creating the config I need.

**Comment by e3eli3h** [comment] 2018-09-06 14:45
@moul, btw, only the new dev build works.
The static build does not given what I have said in my previous post.

**Comment by e3eli3h** [comment] 2018-09-06 14:55
Can I give you more feedback if it will help this project?

For instance, GatewayConnectTimeout does not work when placed in defaults.
It is only working inside a host definition.

**Comment by e3eli3h** [comment] 2018-09-07 10:01
Well it seems that my defaults were not being applied at all due my own stupidity and wrong yml indentation.

Please make it possible to add GatewayConnectTimeout to defaults as this is ignored at present.

**Comment by moul** [comment] 2018-11-25 08:58
Hi @e3eli3h,

`GatewayConnectTimeout` is inherited from defaults as soon as the current host does not have a `GatewayConnectTimeout` set, or if it is set as `0`

Closing this issue as I can't reproduce it

But feel free to reopen it or reopen a new one if you still have problems

**Closed by moul** 2018-11-25 08:58 UTC
Labels: Bug
