### ISSUE TITLE
examples for regex usage

### ISSUE THREAD

**Issue by jakeo** [moul/advanced-ssh-config#121] opened 2016-02-24 20:38 UTC
I'm failing at finding any examples like in the Python version on how to use regex for `Host:`.

I've tried a simple test:

```
  vm-[0-9]:
    HostName: 192.168.1.155
    Port: 2222
```

And while it matches, it's not picking up the port.

Any help here? Thanks!

**Comment by moul** [comment] 2016-02-25 00:57
Hi @jakeo, thank you for reporting,

So I just analyzed the issue, the problem is that **ssh** will always call set the "%p" in the `ProxyCommand`, so if you do not add a `-p 12345` in your cmdline, it will pass `%p=22` by default.

---

Here, a quick demo:

```console
$ assh proxy vm-5 --dry-run
FATA[0000] Proxy error: dry-run: Golang native TCP connection to '192.168.1.155:2222'
$ ssh -v vm-5
...
INFO[0000] Host vm-5
INFO[0000]   Port 22
INFO[0000]   # HostName: 192.168.1.155
...
```

---

I just opened a new issue (#122) to fix this.

---

For now, I suggest you to use one of these alternatives:

* Switch to this configuration file:

    ```yaml
      vm-[0-9]:
        ProxyCommand: nc 192.168.1.155 2222
    ```

    It keeps your advanced regex and matches with your example, but it won't support additional fields (`IdentityFile` for instance).

    or
* switch from `vm-[0-9]` to `vm-*` if you can use more simple regex, this way you will have full **ssh** options support

**Comment by moul** [comment] 2016-03-23 14:11
Closing this issue in favor of #122, please subscribe to the new issue to keep track of the changes

**Closed by moul** 2016-03-23 14:11 UTC
Labels: Bug
